config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root  'static_pages#main_page'

  resources :tweets

  resources :profiles

  resources :follows, only: :create

  resources :hashtags, only: :show

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, PicUploader
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	include Twitter::Extractor

	def get_hashtags 
		self.extract_hashtags(self.content)
	end

	belongs_to :user
	validates :content, length: { maximum: 140 }

	validate :hashtags_are_created

	def hashtags_are_created 
		begin
			transaction do 
				@hashtags = self.get_hashtags
				@hashtags.each do |the_hashtag|
					# find sthg that meets the criteria
					if Hashtag.where(tag: the_hashtag).any?
						# do nothing
					else 
						#create the hashtag
						# ! because if the code doesn't work then rollback, breaks the code
						if Hashtag.create!(tag: the_hashtag)
							# do nothing 
						else 
							# throw an error if for whatever reason, the hashtag couldn't be made 
							# for the users, not real users, don't create it... Not a code error! 
							self.errors.add(:base, "Your hashtag #{the_hashtag} cannot be created")
						end
					end 
				end 
		    end 
		rescue   
			self.errors.add(:base, "Your tweet has a bad hashtag")
		end 
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets 
  has_one :profile

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def create 
		@user = User.find(params[:follows][:user])
		# follow the current user as per the github page
		current_user.follow(@user)
		redirect_to tweets_path
	end 
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

	def show 
		@hashtag = Hashtag.where(tag: params[:id]).first
		@tweets = Tweet.all

		if @hashtag
			@filtered_tweets = @tweets.select do |tweet| 
				tweet.get_hashtags.include?(@hashtag.tag)
			end
		else
			@filtered_tweets = Array.new 
			flash.now[:notice] = "There are no tweets with #{pamrams[:id]}"
		end
	end 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
	before_action :authenticate_user!

	def new 
		@profile = Profile.new
	end

	def create 
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if @profile.save
			flash[:success] = "You have created a profile! :D"
			# render vs redirect ? 
			redirect_to profile_path(current_user.profile)
		else 
			# redirect_to new_tweet_path
			# YOU CAN'T SAY REDIRECT HERE BECAUSE WE NEED TO KEEP TRACK OF THE @TWEET EVEN IT'S LONG SO THAT THE USER 
			# DOESN'T HAVE TO TYPE EVERYTHING ALL OVER AGAIN
			render 'new'
		end
	end 

	def profile_params
		params.require(:profile).permit(:description, :first_name, :picture)
	end 

	# It's a part of resources 
	def show 
		@profile = Profile.find(params[:id])
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	def main_page
		if user_signed_in?
			if current_user.profile
				redirect_to new_tweet_path
			else
				redirect_to new_profile_path
			end
		end
	end
	
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	
	# To make sure the user is signed in first! 
	before_action :authenticate_user!

	def new
		# Create a new instance of the class Tweet that we just created as a model
		@tweet = Tweet.new 
		@testing = Tweet.all
	end

	def create
		# This @tweet has no idea that the other @tweet in the othe action. THEY ARE DIFFRENT AND HAVE NOTHING TO DO WITH EACH OTHER!!!! 
		@tweet = Tweet.new(tweet_params)
		@testing = Tweet.all
		@tweet.user = current_user
		if @tweet.save
			flash[:success] = "You have created a tweet!"
			# render vs redirect ? 
			redirect_to new_tweet_path
		else 
			# redirect_to new_tweet_path
			# YOU CAN'T SAY REDIRECT HERE BECAUSE WE NEED TO KEEP TRACK OF THE @TWEET EVEN IT'S LONG SO THAT THE USER 
			# DOESN'T HAVE TO TYPE EVERYTHING ALL OVER AGAIN
			render 'new'
		end
		# render 'new'
	end

	def tweet_params
		params.require(:tweet).permit(:content)
	end

	def index 
		@tweets = Tweet.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# nav_link instead of link to
	def nav_link(link_text, link_path)

		# current page is build it rails
		class_name = current_page?(link_path) ? 'active' : ''

		#content tag turns ruby into html better, can't use html since it's not .erb
		# returns 
		content_tag(:li, :class => class_name) do
			link_to link_text, link_path
		end
	end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/show.html.erb
<ul class="list-group">
	<% @filtered_tweets.each do |tweet| %>
		<% if tweet.user.profile %>
			<li class="list-group-item">
				<%= tweet.content %> | <%= tweet.user.email %> | <%= link_to tweet.user.profile.first_name, profile_path(tweet.user.profile) %>| 
				<% if current_user.following?(tweet.user) %>
					<button type="button" class="btn btn-danger">
						Already Following
					</button>
				<% else %> 
					<%= simple_form_for :follows, url: follows_path do |f| %>  
					<%= f.input :user, as: :hidden, input_html: {value: tweet.user.id} %>
					<%= f.button :submit, value: 'Follow', class: 'btn btn-large btn-success' %>
				<% end %>
				<% end %>
			</li>
		<% end %>
	<% end %> 
</ul>

\

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Htwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body style='background-image: url("../assets/background.jpg")'>	
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ILab Twitter", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    	<% if user_signed_in? %>
	      <ul class="nav navbar-nav">
	        <li class="active">
	        	<!-- nav link because we are doing the helper thing  -->
	        	<%= nav_link "New Tweet", new_tweet_path %>
	        </li>
	        <li>
	        	<!-- nav link because we are doing the helper thing  -->
	        	<%= nav_link  "News Feed", tweets_path %>
	        	<!-- <a href="#">Link</a> -->
	        </li>
	        <% if current_user.profile %>
	            <li>
	            	<%= nav_link "My profile", profile_path(current_user.profile)%>
	            </li>
        	<% end %>
	        <!-- <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li> -->
	      </ul>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
        	<% if user_signed_in? %>
        		<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        	<% else %>
        		<%= link_to "Sign In", new_user_session_path %>
        	<%end%> 
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li> 
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if params[:action] == 'main_page' %>
  <% flash.each do |key,value| %>
        <div class ="alert alert-<%=key%>">
          <%= value %>
        </div>
      <%end%>
      <%= yield %>
<% else %>
  <div class="container" style="margin-top: 60px;">
  		<% flash.each do |key,value| %>
  		  <div class ="alert alert-<%=key%>">
  			 <%= value %>
  		  </div>
  	   <%end%>
      <%= yield %>
    </div>
<% end %> 

</body>
</html>

app/views/profiles/new.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :picture %>
  <%= f.input :first_name %>
  <%= f.input :description %>
  <%= f.button :submit, value: "Create Profile", class: "btn btn-large btn-primary" %>
<% end %>

app/views/profiles/show.html.erb
<h1> Profile </h1>
<h3> <%= @profile.first_name %> | <%= @profile.user.email %>	 </h3>
<ul class="list-group">
	<li class="list-group-item">
			<%= @profile.description %>	
	</li>	
</ul>
<%= image_tag @profile.picture %>

app/views/static_pages/main_page.html.erb
<!-- Header -->
<header id="top" class="header">
    <div class="text-vertical-center">
        <h1>Welcome to the ILab</h1>
        <h3>Let's rebuild Twitter together :)</h3>
        <br>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-lg btn-dark'%> 
    </div>
</header>

app/views/tweets/index.html.erb
<ul class="list-group">
	<% @tweets.each do |tweet| %>
		<% if tweet.user.profile %>
			<li class="list-group-item">
				<%= tweet.content %> | <%= tweet.user.email %> | <%= link_to tweet.user.profile.first_name, profile_path(tweet.user.profile) %>| 
				<% if current_user.following?(tweet.user) %>
					<button type="button" class="btn btn-danger">
						Already Following
					</button>
				<% else %> 
					<%= simple_form_for :follows, url: follows_path do |f| %>  
					<%= f.input :user, as: :hidden, input_html: {value: tweet.user.id} %>
					<%= f.button :submit, value: 'Follow', class: 'btn btn-large btn-success' %>
				<% end %>
				<% end %>
			</li>
		<% end %>
	<% end %> 
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, value: "Create Tweet", class: "btn btn-large btn-success" %>
<% end %>

<ul class="list-group">
	<% @testing.each do |test| %>
		<li class="list-group-item">
			<%= test.content %> | <%= test.user.email %>
		</li>
	<% end %> 
</ul>